[package]
name = "misskey_client"
version = "0.1.0"
edition = "2021"

[features]
default = []
debug_logging = ["log", "fern"]
log = ["dep:log", "fern"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = {version = "0.4.38", features = ["serde"]}
derive-getters = "0.5.0"
fern = { version = "0.7.0", optional = true }
itertools = "0.13.0"
log = {version = "0.4.22", optional = true }
native-tls = "0.2.11"
serde = "1.0.198"
serde_derive = "1.0.201"
serde_json = "1.0.117"
